    export const formStyles = {
    page: {
        minHeight: '100vh',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'flex-start',
        background: '#f0f0f0',
        padding: '24px 16px',
        fontFamily: '"DM Sans", system-ui, -apple-system, sans-serif',
    },
    card: {
        width: '100%',
        maxWidth: '560px',
        background: '#ffffff',
        padding: '24px',
        borderRadius: '22px',
        boxShadow: '0 12px 40px rgba(0,0,0,0.09)',
        display: 'flex',
        flexDirection: 'column',
        gap: '14px',
        border: '1px solid #e8e8e8',
    },
    input: {
        padding: '12px 14px',
        borderRadius: '12px',
        border: '1.5px solid #e0e0e0',
        fontSize: '14px',
        width: '100%',
        boxSizing: 'border-box',
        background: '#fafafa',
        outline: 'none',
        color: '#111',
        appearance: 'none',
        WebkitAppearance: 'none',
        transition: 'border-color 0.15s',
    },
    button: {
        padding: '13px',
        borderRadius: '12px',
        border: 'none',
        background: '#c80815',
        color: '#fff',
        fontWeight: '700',
        cursor: 'pointer',
        fontSize: '14px',
        letterSpacing: '0.2px',
        transition: 'opacity 0.15s',
    },
    secondaryButton: {
        padding: '11px',
        borderRadius: '12px',
        border: '1.5px solid #ddd',
        background: '#fff',
        color: '#555',
        fontWeight: '700',
        cursor: 'pointer',
        fontSize: '14px',
        transition: 'border-color 0.15s',
    },
    // Kept for backward compat but components now use inline message styles
    message: {
        fontSize: '13px',
        color: '#444',
        marginTop: '2px',
        background: '#fafafa',
        border: '1px solid #eee',
        borderRadius: '10px',
        padding: '10px 12px',
    },
    formSection: {
        borderTop: '1px solid #f0f0f0',
        paddingTop: '14px',
        display: 'flex',
        flexDirection: 'column',
        gap: '10px',
    },
    listSection: {
        borderTop: '1px solid #f0f0f0',
        paddingTop: '14px',
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    listItem: {
        display: 'flex',
        justifyContent: 'space-between',
        padding: '12px 14px',
        border: '1px solid #efefef',
        borderRadius: '12px',
        background: '#fafafa',
    },
    headerBadge: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: '6px',
        padding: '4px 10px',
        borderRadius: '999px',
        background: '#fdecee',
        color: '#c80815',
        fontSize: '11px',
        fontWeight: '700',
        width: 'fit-content',
    },
    headerTitle: {
        fontSize: '28px',
        fontWeight: '900',
        color: '#c80815',
        margin: 0,
        letterSpacing: '-0.5px',
    },
    subText: {
        fontSize: '13px',
        color: '#777',
        margin: 0,
    },
    };